# Generated by Django 5.2.17 on 2026-08-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productevent",
            new_name="product_eve_event_n_32ca9f_idx",
            old_name="product_ev_event_n_55d08d_idx",
        ),
        migrations.RenameIndex(
            model_name="productevent",
            new_name="product_eve_session_7b7295_idx",
            old_name="product_ev_session_3f14f4_idx",
        ),
    ]
