# Generated by Django 5.2.17 on 2026-08-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0002_rename_product_ev_event_n_55d08d_idx_product_eve_event_n_32ca9f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invité"),
                            ("active", "Actif"),
                            ("completed", "Terminé"),
                            ("withdrawn", "Retiré"),
                        ],
                        default="invited",
                        max_length=12,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot_participation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pilot_participants",
                "ordering": ["-invited_at"],
            },
        ),
    ]
