# Generated by Django 5.2.17 on 2026-08-31 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsibleGamingAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("limits_updated", "Mise à jour des limites"),
                            ("cooling_off_activated", "Activation pause temporaire"),
                            ("self_exclusion_activated", "Activation auto-exclusion"),
                            ("cooling_off_expired", "Fin de pause temporaire"),
                            ("self_exclusion_expired", "Fin d'auto-exclusion"),
                            ("deposit_blocked_limit", "Dépôt bloqué (plafond atteint)"),
                            ("game_blocked_exclusion", "Jeu bloqué (auto-exclusion)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_gaming_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responsible_gaming_audits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponsibleGamingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_deposit_limit",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Plafond de dépôt journalier (Ar)",
                        null=True,
                    ),
                ),
                (
                    "weekly_deposit_limit",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Plafond de dépôt hebdomadaire (Ar)",
                        null=True,
                    ),
                ),
                (
                    "monthly_deposit_limit",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Plafond de dépôt mensuel (Ar)", null=True
                    ),
                ),
                (
                    "daily_loss_limit",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Plafond de perte journalière (Ar)",
                        null=True,
                    ),
                ),
                (
                    "daily_bet_limit",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Plafond de mise journalière (Ar)",
                        null=True,
                    ),
                ),
                (
                    "session_time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Durée max par session (min)", null=True
                    ),
                ),
                (
                    "reality_check_interval_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Intervalle de rappel réalité (min)"
                    ),
                ),
                ("cooling_off_until", models.DateTimeField(blank=True, null=True)),
                ("cooling_off_started_at", models.DateTimeField(blank=True, null=True)),
                ("cooling_off_reason", models.CharField(blank=True, max_length=255)),
                ("self_exclusion_until", models.DateTimeField(blank=True, null=True)),
                (
                    "self_exclusion_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_permanently_excluded", models.BooleanField(default=False)),
                ("self_exclusion_reason", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_gaming_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responsible_gaming_profiles",
            },
        ),
    ]
