# Generated by Django 5.2.17 on 2026-08-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallet_tran_user_id_1da2e3_idx",
            old_name="wallet_trans_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallet_tran_status_c987ce_idx",
            old_name="wallet_trans_status_idx",
        ),
    ]
