# Generated by Django 5.2.17 on 2026-08-11 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gameresult"),
        (
            "wallet",
            "0002_rename_wallet_trans_user_created_idx_wallet_tran_user_id_1da2e3_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_key", models.CharField(max_length=40)),
                ("mission_date", models.DateField()),
                ("amount", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reward_claims",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reward_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_reward_claims",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mission_key", "mission_date"),
                        name="unique_daily_reward_claim",
                    )
                ],
            },
        ),
    ]
