# Generated by Django 5.2.17 on 2026-08-11 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_dailyrewardclaim"),
        (
            "wallet",
            "0002_rename_wallet_trans_user_created_idx_wallet_tran_user_id_1da2e3_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("draw_type", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("closed", "Clôturé"),
                            ("drawn", "Tiré"),
                            ("settled", "Réglé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("entry_cost", models.PositiveBigIntegerField(default=0)),
                ("closes_at", models.DateTimeField()),
                ("rules", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "draw_definitions",
                "ordering": ["closes_at"],
            },
        ),
        migrations.CreateModel(
            name="InstantGameDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("game_type", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("cost", models.PositiveBigIntegerField(default=0)),
                ("max_prize", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "En pause")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("rules", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "instant_game_definitions",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="DrawResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbers", models.JSONField(default=list)),
                ("commitment", models.CharField(max_length=128)),
                ("proof", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="games.drawdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "draw_results",
            },
        ),
        migrations.CreateModel(
            name="DrawEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("numbers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="games.drawdefinition",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_entries",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draw_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["draw", "user"], name="draw_entrie_draw_id_4ef084_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InstantPlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Terminée"), ("failed", "Échouée")],
                        max_length=20,
                    ),
                ),
                ("result_kind", models.CharField(max_length=40)),
                ("result_label", models.CharField(max_length=120)),
                ("cost", models.PositiveBigIntegerField(default=0)),
                ("prize", models.PositiveBigIntegerField(default=0)),
                ("audit", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plays",
                        to="games.instantgamedefinition",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instant_plays",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instant_plays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "instant_plays",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="instant_pla_user_id_fbcfad_idx",
                    )
                ],
            },
        ),
    ]
