# Generated by Django 5.2.17 on 2026-08-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("games", "0005_playerpresence_matchmakingticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametable",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="clubs.club",
            ),
        ),
    ]
