# Generated by Django 5.2.17 on 2026-08-13 08:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gametable_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSimulationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("poker", "Poker"),
                            ("belote", "Belote"),
                            ("rami", "Rami"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("tutorial", "Tutoriel"),
                            ("balanced", "Équilibré"),
                            ("expert", "Expert"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_simulation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_simulation",
                        to="games.gametable",
                    ),
                ),
            ],
            options={
                "db_table": "bot_simulation_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotSimulationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_key", models.CharField(max_length=40)),
                ("display_name", models.CharField(max_length=80)),
                ("seat_index", models.PositiveSmallIntegerField()),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("tutorial", "Tutoriel"),
                            ("balanced", "Équilibré"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_bot", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots",
                        to="games.botsimulationsession",
                    ),
                ),
            ],
            options={
                "db_table": "bot_simulation_participants",
            },
        ),
        migrations.AddConstraint(
            model_name="botsimulationsession",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"),
                name="unique_bot_simulation_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="botsimulationparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "seat_index"), name="unique_bot_simulation_seat"
            ),
        ),
        migrations.AddConstraint(
            model_name="botsimulationparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "bot_key"), name="unique_bot_simulation_bot"
            ),
        ),
    ]
