import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, LifeBuoy, Send } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useGameStore } from '@stores/gameStore'
import { createSupportTicket, getSupportTickets, type SupportTicket } from '@services/support'

export function SupportPage() {
  const token = useGameStore((state) => state.accessToken)
  const [tickets, setTickets] = useState<SupportTicket[]>([]); const [category, setCategory] = useState('other'); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { if (token) getSupportTickets(token).then((result) => setTickets(result.results)).catch((error: Error) => setMessage(error.message)) }, [token])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!token) { setMessage('Connectez-vous pour ouvrir un ticket.'); return }; setLoading(true); try { await createSupportTicket(token, category, subject, description); setMessage('Votre ticket a été envoyé.'); setSubject(''); setDescription(''); const result = await getSupportTickets(token); setTickets(result.results) } catch (error) { setMessage(error instanceof Error ? error.message : 'Ticket impossible.') } finally { setLoading(false) } }
  return <div className="page-stack"><div className="page-title-row"><div><span className="eyebrow"><LifeBuoy size={13}/> Support</span><h1>Besoin d’<em>aide ?</em></h1><p>Décrivez votre demande, notre équipe pourra la suivre depuis le club.</p></div><Link to="/profile" className="back-link"><ArrowLeft size={16}/> Retour au profil</Link></div><div className="wallet-layout"><form className="payment-card" onSubmit={submit}><h3>Ouvrir un ticket</h3><label className="field-label">Catégorie<select className="auth-name-field" value={category} onChange={(event) => setCategory(event.target.value)}><option value="account">Compte</option><option value="wallet">Portefeuille</option><option value="game">Partie</option><option value="other">Autre</option></select></label><label className="field-label">Sujet<input className="auth-name-field" required maxLength={120} value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Ex. Question sur une partie"/></label><label className="field-label">Description<textarea className="auth-name-field" required maxLength={2000} rows={6} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Expliquez votre demande…"/></label><button className="button button-gold" disabled={loading}><Send size={16}/> {loading ? 'Envoi…' : 'Envoyer le ticket'}</button>{message && <p className="secure-note">{message}</p>}</form><section className="activity-card"><div className="chat-head">Vos tickets</div>{tickets.length ? tickets.map((ticket) => <div className="activity-row" key={ticket.id}><div><strong>{ticket.subject}</strong><span>{ticket.category} · {ticket.status}</span></div><small>{new Date(ticket.created_at).toLocaleDateString('fr-FR')}</small></div>) : <div className="empty-wallet">Aucun ticket pour le moment.</div>}</section></div></div>
}
