# Generated by Django 5.2.17 on 2026-08-31 17:00

import apps.kyc.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kycrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kycrequest",
            name="reviewer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="kycrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvée"),
                    ("rejected", "Refusée"),
                    ("resubmission_requested", "Complément requis"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id_front", "CIN (Recto)"),
                            ("national_id_back", "CIN (Verso)"),
                            ("passport", "Passeport"),
                            ("proof_of_residence", "Certificat de résidence"),
                            ("selfie_with_id", "Selfie avec pièce d'identité"),
                            (
                                "source_of_funds",
                                "Justificatif de revenus / Source de fonds",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.kyc.models.kyc_document_upload_path
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="Taille en octets"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "file_hash",
                    models.CharField(db_index=True, help_text="SHA-256", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours de vérification"),
                            ("valid", "Conforme"),
                            ("rejected", "Non conforme"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kyc_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="kyc.kycrequest",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_documents",
                "ordering": ["created_at"],
            },
        ),
    ]
