# Generated by Django 5.2.17 on 2026-08-12 10:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ClubEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=280)),
                ("starts_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(default=16)),
                ("points_reward", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Planifié"), ("completed", "Terminé")],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "club_events",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubEventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="clubs.clubevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_event_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "club_event_participants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_club_event_participant"
                    )
                ],
            },
        ),
    ]
