# Generated by Django 5.2.17 on 2026-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_clubmembership_points_clubevent_clubeventparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubeventparticipant",
            name="rewarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
