# Generated by Django 5.2.17 on 2026-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="checkout_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="error_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="provider_reference",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="amount",
            field=models.PositiveBigIntegerField(help_text="Montant en Ariary (MGA)"),
        ),
    ]
